<a href="https://colab.research.google.com/github/UnessR/Workshop_AI_UnessRawat/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Problem 1
import numpy as np
# 1
a = np.array([[1,2],[3,4]])
print(a)
# 2
b = np.ones((4,2))
print(b)
# 3
c = np.full((2,2),4)
print(c)
# 4
d = np.zeros_like(a)
print(d)
# 5
e = np.ones_like(a)
print(e)
# 6
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
# problem2
import numpy as np
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
arr = np.arange(0,9)
print(arr)
matrix = arr.reshape(3,3)
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.random.random(30)
mean_value = arr.mean()

print("Array:", arr)
print("Mean:", mean_value)


Array: [0.2238247  0.86191057 0.81887664 0.80124492 0.36894892 0.77227463
 0.02975305 0.92686639 0.17685365 0.88534249 0.96739275 0.21986443
 0.44318698 0.82681787 0.40898715 0.32267013 0.94774836 0.33282766
 0.17249049 0.82898216 0.88158906 0.42219453 0.02290929 0.50160847
 0.44315328 0.58098839 0.89050563 0.32286498 0.59469913 0.48718401]
Mean: 0.5494853563504524


In [ ]:
import numpy as np

arr = np.random.random((10,10))

print(arr)

min = arr.min()
max = arr.max()

print("Minimum value: ",min)
print("Maximum value: ",max)

[[0.66156533 0.61777045 0.92653298 0.07285337 0.91839686 0.60008832
  0.84887665 0.79467667 0.78289765 0.1601796 ]
 [0.6754191  0.96802717 0.13155265 0.0224929  0.18062433 0.66782756
  0.67255333 0.41177665 0.01141362 0.34325176]
 [0.67214232 0.75262989 0.48225798 0.71698191 0.27436225 0.65464051
  0.99482359 0.26399932 0.86595341 0.0307167 ]
 [0.07782297 0.74026724 0.88723062 0.36211281 0.8335882  0.0316506
  0.02172041 0.0113979  0.65869717 0.13344537]
 [0.86149592 0.12796245 0.64833809 0.32714294 0.40746223 0.8487442
  0.22330282 0.16250735 0.50265268 0.77846401]
 [0.03739015 0.7929458  0.88753691 0.96644746 0.54385476 0.28172408
  0.159746   0.53223127 0.01621924 0.38608721]
 [0.38541616 0.51041408 0.6508085  0.91851334 0.80806265 0.12334103
  0.33881287 0.08681038 0.83273734 0.02856082]
 [0.36008698 0.62847999 0.42619396 0.59510354 0.98891654 0.62817364
  0.02301658 0.04346849 0.09234727 0.18897707]
 [0.93572792 0.50845821 0.43232866 0.67138477 0.53791035 0.45661777
  0.935748   0

In [ ]:
import numpy as np

arr = np.zeros(10)
print(arr)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = [1,2,0,0,4,0]

reversed = np.flip(arr)
print(reversed)

[0 4 0 0 2 1]


In [ ]:
import numpy as np

rows, cols = 5, 5
arr = np.ones((rows, cols), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # odd rows, even columns
checkerboard[::2, 1::2] = 1  # even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# problem3
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1 add
addition = x + y
print(addition)

#2 subtract
subtraction = x - y
print(subtraction)

#3 multiplication
multiplication = x * 3
multiplication_1 = v * 2
print(multiplication)
print(multiplication_1)

#4 square
square_x = x ** 2
print(square_x)

#dot product
VandW = np.dot(v,w)
print("dot product between v and w: ", VandW)

XandV = np.dot(x,v)
print("dot product between X and V: ", XandV)

XandY = np.dot(x,y)
print("dot product between X and Y: \n", XandY)

#6 concatination
XwithY = np.vstack((x,y))
print(XwithY)

VwithW = np.column_stack((v,w))
print(VwithW)

#7
xwithv = np.concatenate((x, v), axis=0)
#ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
#Concatenation in NumPy requires arrays to have the same number of dimensions.


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[18 20]
[[ 1  4]
 [ 9 25]]
dot product between v and w:  219
dot product between X and V:  [29 77]
dot product between X and Y: 
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#problem4
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

I = np.eye(2, dtype=int)

A_inv = np.linalg.inv(A)
AdotAinv = np.dot(A,A_inv)
AdotAinv_int = np.round(AdotAinv).astype(int)
print(AdotAinv_int)

if np.array_equal(AdotAinv_int, I):
    print("True")
else:
    print("False")

[[1 0]
 [0 1]]
True


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AdotB = np.dot(A,B)
BdotA = np.dot(B,A)

print(AdotB)
print(BdotA)

if np.array_equal(AdotB, BdotA):
    print("Both are equal")
else:
    print("Not equal")


[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Not equal


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A, B)
AB_T = AB.T
print("(AB)^T =\n", AB_T)

B_T = B.T
A_T = A.T

BTA_T = np.dot(B_T, A_T)
print("B^T · A^T =\n", BTA_T)

if np.array_equal(AB_T, BTA_T):
    print("Property Verified: (AB)^T = B^T A^T")
else:
    print("Property Not Verified")


(AB)^T =
 [[23 51]
 [13 29]]
B^T · A^T =
 [[23 51]
 [13 29]]
Property Verified: (AB)^T = B^T A^T


In [ ]:
#solving linera equation
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-3],[9]])

Ainv = np.linalg.inv(A)
x = np.dot(Ainv,B)

print(x)

[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
#Experiment

import time
import numpy as np

list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()

list_result = [list1[i] + list2[i] for i in range(1_000_000)]

end_time = time.time()

print("Time taken for element-wise addition using Python lists:",
      end_time - start_time, "seconds")

#using numpy
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()

arr_result = arr1 + arr2

end_time = time.time()

print("Time taken using NumPy arrays:",
      end_time - start_time, "seconds")

Time taken for element-wise addition using Python lists: 0.19912195205688477 seconds
Time taken using NumPy arrays: 0.005364894866943359 seconds


In [ ]:
#element wise multiplication

import time
import numpy as np

list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()

list_result = [list1[i] * list2[i] for i in range(1_000_000)]

end_time = time.time()

print("Time taken for element-wise addition using Python lists:",
      end_time - start_time, "seconds")

#using numpy
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()

arr_result = arr1 * arr2

end_time = time.time()

print("Time taken using NumPy arrays:",
      end_time - start_time, "seconds")

Time taken for element-wise addition using Python lists: 0.24791455268859863 seconds
Time taken using NumPy arrays: 0.005281209945678711 seconds


In [ ]:
import time
import numpy as np

list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()

dot_product_list = 0
for i in range(1_000_000):
    dot_product_list += list1[i] * list2[i]

end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken (Python lists):", end_time - start_time, "seconds")

#using numpy
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)

end_time = time.time()

print("\nDot product using NumPy:", dot_product_numpy)
print("Time taken (NumPy):", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken (Python lists): 0.4017651081085205 seconds

Dot product using NumPy: 333332833333500000
Time taken (NumPy): 0.0024118423461914062 seconds


In [ ]:
import time
import numpy as np
import random

size = 1000
matrix1 = [[random.randint(0, 9) for i in range(size)] for i in range(size)]
matrix2 = [[random.randint(0, 9) for i in range(size)] for i in range(size)]

start_time = time.time()

result_list = [[0]*size for i in range(size)]

for i in range(size):
    for j in range(size):
        sum_val = 0
        for k in range(size):
            sum_val += matrix1[i][k] * matrix2[k][j]
        result_list[i][j] = sum_val

end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")

#using numpy
arr1 = np.array(matrix1)
arr2 = np.array(matrix2)

start_time = time.time()

result_numpy = np.dot(arr1, arr2)

end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds")
